test: This is nothing

test2:
  test22: this is something

dataset:
  maxPerClass: 1000000

doodle:
  stats: 'persistentCache/classes50stats.dill'
  modelPath: './classifiers/models/Basic-ss50-3-model-test.h5'
  weightPath: './classifiers/models/Basic-ss50-3-weight.h5'